# Generated by Django 3.2.25 on 2026-03-25 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(db_column='ID_ABSENCE', primary_key=True, serialize=False)),
                ('date_absence', models.DateField(db_column='DATE_ABSENCE')),
                ('est_justifiee', models.IntegerField(db_column='EST_JUSTIFIEE', default=0)),
                ('motif', models.CharField(blank=True, db_column='MOTIF', max_length=200, null=True)),
                ('date_saisie', models.DateField(auto_now_add=True, db_column='DATE_SAISIE')),
                ('saisi_par', models.CharField(blank=True, db_column='SAISI_PAR', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ABSENCES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_audit', models.AutoField(db_column='ID_AUDIT', primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_column='TABLE_NAME', max_length=50)),
                ('operation', models.CharField(db_column='OPERATION', max_length=10)),
                ('record_id', models.IntegerField(blank=True, db_column='RECORD_ID', null=True)),
                ('old_values', models.TextField(blank=True, db_column='OLD_VALUES', null=True)),
                ('new_values', models.TextField(blank=True, db_column='NEW_VALUES', null=True)),
                ('utilisateur', models.CharField(blank=True, db_column='UTILISATEUR', max_length=50, null=True)),
                ('date_operation', models.DateTimeField(db_column='DATE_OPERATION')),
            ],
            options={
                'db_table': 'AUDIT_LOG',
                'ordering': ['-date_operation'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_enseignant', models.AutoField(db_column='ID_ENSEIGNANT', primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_column='MATRICULE', max_length=20, unique=True)),
                ('nom', models.CharField(db_column='NOM', max_length=50)),
                ('prenom', models.CharField(db_column='PRENOM', max_length=50)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, db_column='TELEPHONE', max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, db_column='SPECIALITE', max_length=100, null=True)),
                ('grade', models.CharField(blank=True, db_column='GRADE', max_length=50, null=True)),
                ('statut', models.CharField(db_column='STATUT', default='ACTIF', max_length=20)),
            ],
            options={
                'db_table': 'ENSEIGNANTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(db_column='ID_ETUDIANT', primary_key=True, serialize=False)),
                ('cne', models.CharField(db_column='CNE', max_length=20, unique=True)),
                ('nom', models.CharField(db_column='NOM', max_length=50)),
                ('prenom', models.CharField(db_column='PRENOM', max_length=50)),
                ('date_naissance', models.DateField(db_column='DATE_NAISSANCE')),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, db_column='TELEPHONE', max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, db_column='ADRESSE', max_length=200, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('DIPLOME', 'Diplômé')], db_column='STATUT', default='ACTIF', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True, db_column='DATE_INSCRIPTION')),
            ],
            options={
                'db_table': 'ETUDIANTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(db_column='ID_FILIERE', primary_key=True, serialize=False)),
                ('code_filiere', models.CharField(db_column='CODE_FILIERE', max_length=20, unique=True)),
                ('nom_filiere', models.CharField(db_column='NOM_FILIERE', max_length=100)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=500, null=True)),
                ('date_creation', models.DateField(auto_now_add=True, db_column='DATE_CREATION')),
            ],
            options={
                'db_table': 'FILIERES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.AutoField(db_column='ID_GROUPE', primary_key=True, serialize=False)),
                ('code_groupe', models.CharField(db_column='CODE_GROUPE', max_length=20, unique=True)),
                ('nom_groupe', models.CharField(db_column='NOM_GROUPE', max_length=100)),
                ('annee_universitaire', models.CharField(db_column='ANNEE_UNIVERSITAIRE', max_length=9)),
            ],
            options={
                'db_table': 'GROUPES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id_justificatif', models.AutoField(db_column='ID_JUSTIFICATIF', primary_key=True, serialize=False)),
                ('type_justificatif', models.CharField(db_column='TYPE_JUSTIFICATIF', max_length=50)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=500, null=True)),
                ('fichier_path', models.CharField(blank=True, db_column='FICHIER_PATH', max_length=300, null=True)),
                ('date_soumission', models.DateField(auto_now_add=True, db_column='DATE_SOUMISSION')),
                ('date_traitement', models.DateField(blank=True, db_column='DATE_TRAITEMENT', null=True)),
                ('statut', models.CharField(db_column='STATUT', default='EN_ATTENTE', max_length=20)),
                ('traite_par', models.CharField(blank=True, db_column='TRAITE_PAR', max_length=50, null=True)),
                ('commentaire', models.CharField(blank=True, db_column='COMMENTAIRE', max_length=500, null=True)),
            ],
            options={
                'db_table': 'JUSTIFICATIFS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(db_column='ID_MATIERE', primary_key=True, serialize=False)),
                ('code_matiere', models.CharField(db_column='CODE_MATIERE', max_length=20, unique=True)),
                ('nom_matiere', models.CharField(db_column='NOM_MATIERE', max_length=100)),
                ('coefficient', models.DecimalField(db_column='COEFFICIENT', decimal_places=1, max_digits=3)),
                ('volume_horaire', models.IntegerField(db_column='VOLUME_HORAIRE')),
                ('type_matiere', models.CharField(db_column='TYPE_MATIERE', default='COURS', max_length=20)),
            ],
            options={
                'db_table': 'MATIERES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(db_column='ID_NOTIFICATION', primary_key=True, serialize=False)),
                ('type_notification', models.CharField(db_column='TYPE_NOTIFICATION', max_length=50)),
                ('message', models.CharField(db_column='MESSAGE', max_length=500)),
                ('est_lue', models.IntegerField(db_column='EST_LUE', default=0)),
                ('date_creation', models.DateTimeField(db_column='DATE_CREATION')),
            ],
            options={
                'db_table': 'NOTIFICATIONS',
                'ordering': ['-date_creation'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(db_column='ID_SEANCE', primary_key=True, serialize=False)),
                ('date_seance', models.DateField(db_column='DATE_SEANCE')),
                ('heure_debut', models.CharField(db_column='HEURE_DEBUT', max_length=5)),
                ('heure_fin', models.CharField(db_column='HEURE_FIN', max_length=5)),
                ('salle', models.CharField(blank=True, db_column='SALLE', max_length=30, null=True)),
                ('type_seance', models.CharField(db_column='TYPE_SEANCE', default='COURS', max_length=20)),
                ('statut', models.CharField(db_column='STATUT', default='PLANIFIEE', max_length=20)),
            ],
            options={
                'db_table': 'SEANCES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(db_column='ID_SEMESTRE', primary_key=True, serialize=False)),
                ('code_semestre', models.CharField(db_column='CODE_SEMESTRE', max_length=10, unique=True)),
                ('nom_semestre', models.CharField(db_column='NOM_SEMESTRE', max_length=50)),
                ('date_debut', models.DateField(db_column='DATE_DEBUT')),
                ('date_fin', models.DateField(db_column='DATE_FIN')),
                ('annee_universitaire', models.CharField(db_column='ANNEE_UNIVERSITAIRE', max_length=9)),
            ],
            options={
                'db_table': 'SEMESTRES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant')], default='ETUDIANT', max_length=20)),
                ('id_enseignant', models.ForeignKey(blank=True, db_column='ID_ENSEIGNANT_LINK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='absences.enseignant')),
                ('id_etudiant', models.ForeignKey(blank=True, db_column='ID_ETUDIANT_LINK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='absences.etudiant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_PROFILES',
            },
        ),
    ]
