-- Run as SYSTEM
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Drop user if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP USER gestion_absences CASCADE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create user
CREATE USER gestion_absences IDENTIFIED BY gestion2025
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW TO gestion_absences;
GRANT CREATE SEQUENCE TO gestion_absences;
GRANT CREATE TRIGGER TO gestion_absences;
GRANT CREATE PROCEDURE TO gestion_absences;
GRANT CREATE SESSION TO gestion_absences;

EXIT;
